fix(package): shouldn't ever have supported Angular 5, without rxjs 6. Bump both peerdeps to 6, + tslib.
This isn't a breaking change, because it was always going to fail without RxJs 6.
The functionality was never there to break.

Errors like:

node_modules/angular-skyhook/connection-types.d.ts(8,22): error TS2305: Module '"/Users/cormac/git/cormacrelf/compat-tester/node_modules/rxjs/Rx"' has no exported member 'TeardownLogic'.
node_modules/angular-skyhook/connection-types.d.ts(11,24): error TS2305: Module '"/Users/cormac/git/cormacrelf/compat-tester/node_modules/rxjs/Rx"' has no exported member 'SubscriptionLike'.
node_modules/angular-skyhook/connector.service.d.ts(5,10): error TS2305: Module '"/Users/cormac/git/cormacrelf/compat-tester/node_modules/rxjs/Rx"' has no exported member 'SubscriptionLike'.
node_modules/angular-skyhook/connector.service.d.ts(5,28): error TS2305: Module '"/Users/cormac/git/cormacrelf/compat-tester/node_modules/rxjs/Rx"' has no exported member 'TeardownLogic'.